import { Router } from "express";
import { authRouter } from "../modules/auth/auth.routes";
import { userRouter } from "../modules/users/user.routes";
import { departmentRouter } from "../modules/departments/department.routes";
import { attendanceRouter } from "../modules/attendance/attendance.routes";
import { leaveRouter } from "../modules/leave/leave.routes";
import { payrollRouter } from "../modules/payroll/payroll.routes";
import { reimbursementRouter } from "../modules/reimbursements/reimbursement.routes";
import { paymentRouter, paymentWebhookRouter } from "../modules/payments/payment.routes";
import { notificationRouter } from "../modules/notifications/notification.routes";
import { auditRouter } from "../modules/audit/audit.routes";
import { reportRouter } from "../modules/reports/report.routes";
import { fileRouter } from "../modules/files/file.routes";
import { holidayRouter } from "../modules/holidays/holiday.routes";
import { performanceRouter } from "../modules/performance/performance.routes";
import { gamificationRouter } from "../modules/gamification/gamification.routes";
import { helpdeskRouter } from "../modules/helpdesk/helpdesk.routes";
import { assetRouter } from "../modules/assets/asset.routes";
import { recruitmentRouter } from "../modules/recruitment/recruitment.routes";
import { settingsRouter } from "../modules/settings/settings.routes";

export const rootRouter = Router();

rootRouter.use("/auth", authRouter);
rootRouter.use("/users", userRouter);
rootRouter.use("/departments", departmentRouter);
rootRouter.use("/attendance", attendanceRouter);
rootRouter.use("/leave", leaveRouter);
rootRouter.use("/payroll", payrollRouter);
rootRouter.use("/reimbursements", reimbursementRouter);
rootRouter.use("/payments", paymentRouter);
rootRouter.use("/payments/webhook", paymentWebhookRouter);
rootRouter.use("/notifications", notificationRouter);
rootRouter.use("/audit", auditRouter);
rootRouter.use("/reports", reportRouter);
rootRouter.use("/files", fileRouter);
rootRouter.use("/holidays", holidayRouter);
rootRouter.use("/performance", performanceRouter);
rootRouter.use("/gamification", gamificationRouter);
rootRouter.use("/helpdesk", helpdeskRouter);
rootRouter.use("/assets", assetRouter);
rootRouter.use("/recruitment", recruitmentRouter);
rootRouter.use("/settings", settingsRouter);
